services:
    ntnhan0605:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ntnhan0605
        volumes:
            - ./:/usr/src/app
        ports:
            - 8000:8000
